# Generated by Django 4.2.6 on 2023-10-18 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbcore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inputformmodel',
            options={'verbose_name': 'Модель', 'verbose_name_plural': 'Модель'},
        ),
        migrations.AlterModelOptions(
            name='resultmodelfile',
            options={'verbose_name': 'Результат предсказания', 'verbose_name_plural': 'Результат предсказания'},
        ),
    ]
